runtime: nodejs20
service: default

handlers:
  - url: /(.*\.(js|css|map|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(js|css|map|png|jpg|jpeg|gif|svg|ico|webp|woff|woff2|ttf|eot)$
    secure: always
    http_headers:
      Cache-Control: public, max-age=3600

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      Cache-Control: no-cache, must-revalidate

instance_class: F1

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic

env_variables:
  NODE_ENV: 'production'