steps:
  # Install dependencies and build the frontend
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: 'frontend'
    id: 'Install Dependencies'

  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'
    id: 'Build Frontend'

  # Build the container with buildpacks
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - build
      - '${_IMAGE_NAME}'
      - '--builder=gcr.io/buildpacks/builder:latest'
      - '--path=frontend'
    id: Buildpack

images:
  - '${_IMAGE_NAME}'

substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/tiger21-agents'

options:
  logging: CLOUD_LOGGING_ONLY